name: FRC Unit Test

on:
  push:
    branches:
      - main  # Default branch
      - unit-tests
  pull_request:
      - main
      - unit-tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Make gradlew executable
      run: chmod +x gradlew  # Ensure gradlew is executable

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test
